language: "en-US"

reviews:
  profile: "chill"
  high_level_summary: true
  collapse_walkthrough: true
  poem: false
  review_status: false
  commit_status: false

  auto_review:
    enabled: true
    drafts: false
    labels: ["!wip"]
    ignore_title_keywords: ["wip"]

  finishing_touches:
    docstrings:
      enabled: false

  pre_merge_checks:
    docstrings:
      mode: "off"
    description:
      mode: "off"

chat:
  art: false
