name: Check Package Size

on:
  pull_request:
    branches: [main]

concurrency:
  group: pkg-size-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-size:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Calculate package size
        uses: pkg-size/action@7cbd5229062f24aec6543e0b8fd5eb09233bf355
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
